## input image
|   |||||
|:--|---|---|---|---|
| 1 |2|0|3|1|
|0|1|2|3|1|
|1|2|1|0|0|
|5|2|3|1|1|
|2|1|0|1|1|

---

## 卷積核 3*3
||||
|:--|--|--|
|1|2|1|
|0|1|0|
|2|1|0|

---

## output
|    |    |    |
|:---|----|----|
| 10 | 12 | 12 |
| 18 | 16 | 16 |
| 13 | 9  | 3  |





In [2]:
import torch
input = torch.tensor([[1, 2, 0, 3, 1],
                      [0, 1, 2, 3, 1],
                      [1, 2, 1, 0, 0],
                      [5, 2, 3, 1, 1],
                      [2, 1, 0, 1, 1]])

# 核心
kernel = torch.tensor([[1, 2, 1],
                       [0, 1, 0],
                       [2, 1, 0]])



## batch_size
表示一次处理的样本数量（例如，输入一批图像的个数）。
如果只有单张图像，也要保持 4 维，例如 (1, 3, 224, 224)。
## in_channels
输入数据的通道数，例如：
灰度图像：in_channels=1
RGB 彩色图像：in_channels=3
## height 和 width
输入图像的高度和宽度（单位：像素）。


In [4]:
# input – input tensor of shape(minibatch, in_channels, iH, iW)
input = torch.reshape(input, (1, 1, 5, 5))
kernel = torch.reshape(kernel, (1, 1, 3, 3))
print(input.shape)
print(kernel.shape)

torch.Size([1, 1, 5, 5])
torch.Size([1, 1, 3, 3])


In [5]:
import torch.nn.functional as F

output = F.conv2d(input, kernel, stride=1)
print(output.shape)
print(output)

torch.Size([1, 1, 3, 3])
tensor([[[[10, 12, 12],
          [18, 16, 16],
          [13,  9,  3]]]])


In [6]:
output2 = F.conv2d(input, kernel, stride=2)
print(output2.shape)
print(output2)

torch.Size([1, 1, 2, 2])
tensor([[[[10, 12],
          [13,  3]]]])


相當於input多了一圈為0

In [7]:
output3 = F.conv2d(input, kernel, stride=1, padding=1)
print(output3.shape)
print(output3)

torch.Size([1, 1, 5, 5])
tensor([[[[ 1,  3,  4, 10,  8],
          [ 5, 10, 12, 12,  6],
          [ 7, 18, 16, 16,  8],
          [11, 13,  9,  3,  4],
          [14, 13,  9,  7,  4]]]])
