In [1]:
from torchvision import transforms
from PIL import Image
import cv2


In [2]:

# tensor data type

# img_path = "dataset/practical_data/train/ants_image/0013035.jpg"
img_path = "dataset/practical_data/train/ants_image/5650366_e22b7e1065.jpg"

img = Image.open(img_path) # PIL img data type

cv_img_BGR = cv2.imread(img_path) # numpy data type # BGR cv2的图片默認是BGR
cv_img = cv2.cvtColor(cv_img_BGR, cv2.COLOR_BGR2RGB) # RGB 要轉回RGB

print(img)
print(cv_img)


<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=500x375 at 0x174C8714D90>
[[[ 97 119 106]
  [ 97 119 106]
  [ 98 120 107]
  ...
  [ 87 103  92]
  [ 86 102  91]
  [ 85 101  90]]

 [[ 96 120 107]
  [ 97 119 106]
  [ 98 120 107]
  ...
  [ 90 100  91]
  [ 89  99  90]
  [ 88  98  89]]

 [[ 97 121 108]
  [ 97 121 108]
  [ 98 122 108]
  ...
  [ 95  97  92]
  [ 94  96  91]
  [ 93  95  90]]

 ...

 [[155 152 143]
  [155 152 143]
  [156 153 144]
  ...
  [118 117 112]
  [118 117 112]
  [118 117 112]]

 [[150 150 138]
  [151 151 141]
  [151 151 143]
  ...
  [117 116 111]
  [117 116 111]
  [117 116 111]]

 [[148 148 136]
  [148 148 138]
  [149 148 143]
  ...
  [116 115 110]
  [116 115 110]
  [116 115 110]]]


In [3]:

tensor_trans = transforms.ToTensor()
tensor_img = tensor_trans(img)
tensor_img2 = tensor_trans(cv_img)
print(tensor_img)
print(tensor_img2)
print()
print(type(tensor_img))
print(type(tensor_img2))
print()
print(tensor_img.size(), tensor_img.shape)
print(tensor_img2.size(), tensor_img2.shape)


tensor([[[0.3804, 0.3804, 0.3843,  ..., 0.3412, 0.3373, 0.3333],
         [0.3765, 0.3804, 0.3843,  ..., 0.3529, 0.3490, 0.3451],
         [0.3804, 0.3804, 0.3843,  ..., 0.3725, 0.3686, 0.3647],
         ...,
         [0.6078, 0.6078, 0.6118,  ..., 0.4627, 0.4627, 0.4627],
         [0.5882, 0.5922, 0.5922,  ..., 0.4588, 0.4588, 0.4588],
         [0.5804, 0.5804, 0.5843,  ..., 0.4549, 0.4549, 0.4549]],

        [[0.4667, 0.4667, 0.4706,  ..., 0.4039, 0.4000, 0.3961],
         [0.4706, 0.4667, 0.4706,  ..., 0.3922, 0.3882, 0.3843],
         [0.4745, 0.4745, 0.4784,  ..., 0.3804, 0.3765, 0.3725],
         ...,
         [0.5961, 0.5961, 0.6000,  ..., 0.4588, 0.4588, 0.4588],
         [0.5882, 0.5922, 0.5922,  ..., 0.4549, 0.4549, 0.4549],
         [0.5804, 0.5804, 0.5804,  ..., 0.4510, 0.4510, 0.4510]],

        [[0.4157, 0.4157, 0.4196,  ..., 0.3608, 0.3569, 0.3529],
         [0.4196, 0.4157, 0.4196,  ..., 0.3569, 0.3529, 0.3490],
         [0.4235, 0.4235, 0.4235,  ..., 0.3608, 0.3569, 0.

In [4]:
from torch.utils.tensorboard import SummaryWriter
writer = SummaryWriter("logs")
writer.add_image('image', tensor_img, 1)
writer.add_image('image', tensor_img2, 2)
writer.close()
# cmd: tensorboard --logdir=logs